---

- name: Prepare or update webservers
  hosts: webservers
  user: ansible
  become: yes
  tasks:
    - name: Install or update NGINX
      tags: ubuntu,webservers
      apt:
        name: nginx
        state: latest
        update_cache: yes
      when: ansible_distribution in ["Ubuntu", "Debian"]
    - name: Delete MariaDB if present
      tags: ubuntu,webservers,started
      apt:
        name: mariadb-server
        state: absent
      when: ansible_distribution in ["Ubuntu", "Debian"]
    - name: Copy HTML file to servers
      tags: webservers,upload
      copy:
        src: files/default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
    - name: Start NGINX
      tags: webservers,started
      service:
        name: nginx
        state: started
        enabled: yes

- name: Prepare or update dbservers
  hosts: dbservers
  user: ansible
  become: yes
  tasks:
    - name: Install or update MariaDB
      tags: ubuntu,dbservers
      apt:
        name: mariadb-server
        state: latest
        update_cache: yes
      when: ansible_distribution in ["Ubuntu", "Debian"]
    - name: Start MariaDB
      tags: dbservers,started
      service:
        name: mysql
        state: started
        enabled: yes

- name: Prepare or update fileservers
  hosts: fileservers
  user: ansible
  become: yes
  tasks:
    - name: Install or update Samba
      tags: ubuntu,fileservers
      apt:
        name: samba
        state: latest
        update_cache: yes
      when: ansible_distribution in ["Ubuntu", "Debian"]
    - name: Make sure ansible user is created
      tags: fileservers,user
      user:
        name: samba
        shell: /bin/bash
        append: yes
        state: present
    - name: Copy Samba config file to servers
      tags: fileservers,upload
      copy:
        src: files/smb.conf
        dest: /etc/samba/smb.conf
        owner: root
        group: root
        mode: 0644
      register: new_conf
    - name: Make sure /sambashare directory is created
      tags: fileservers,upload
      file:
        path: "/sambashare"
        state: directory
        owner: root
        group: root
        mode: 0666
    - name: Touch test file
      tags: fileservers,upload
      file:
        path: "/sambashare/hello_there"
        state: touch
        owner: root
        group: root
        mode: 0644
    - name: Start Samba
      tags: fileservers,started
      service:
        name: smbd
        state: started
        enabled: yes
    - name: Restart Samba
      tags: fileservers,started,upload
      service:
        name: smbd
        state: restarted
        enabled: yes
      when: new_conf.changed

- name: Prepare DevTeam's Workstation
  hosts: devteam
  user: ansible
  become: yes
  tasks:
  - name: Make sure user is created
    tags: devteam,user
    user:
      name: "{{ worker }}"
      update_password: on_create
      shell: /bin/bash
      append: yes
      state: present
  - name: Make sure text editor is installed
    tags: devteam
    apt:
      name: "{{ texteditor }}"
      update_cache: yes
   